name: google_exporter
description: An app to export all of your google data
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  dartz: ^0.10.1 # Functional programming in Dart, provides Either, Option types, etc.
  data_table_2: ^2.5.10
  dio: ^5.4.0 # A powerful HTTP client for Dart, used for making network requests.
  equatable: ^2.0.5 # Simplifies equality comparisons, useful for value types.
  file_picker: ^8.0.0+1 # Allows users to pick files from the device.
  flex_color_scheme: ^7.3.1 # Offers theming capabilities with FlexColorScheme.
  flutter:
    sdk: flutter # Flutter SDK
  flutter_adaptive_scaffold: ^0.1.8 # Provides adaptive layout patterns.
  flutter_localizations:
    sdk: flutter # Internationalization support for Flutter.
  flutter_riverpod: ^2.4.9 # State management solution, allowing reactive data flow.
  flutter_speed_dial: ^7.0.0
  freezed: ^2.4.5 # Code generation for immutable objects and sealed classes.
  freezed_annotation: ^2.4.1 # Annotations for Freezed to generate code.
  go_router: ^13.0.1 # Navigation library using declarative routing.
  intl: ^0.18.1 # Internationalization and localization facilities.
  # isar: ^4.0.0-dev.10 # Commented out, possibly for a future upgrade.
  # isar_flutter_libs: ^4.0.0-dev.10 # Commented out, possibly for a future upgrade.
  isar: ^3.1.0+1 # A fast database for Flutter and Dart apps.
  isar_flutter_libs: ^3.1.0+1 # Necessary Flutter libs for Isar.
  json_annotation: ^4.8.1 # Annotations for JSON serialization.
  objectbox: ^2.4.0
  objectbox_flutter_libs: any
  path_provider: ^2.1.1 # Find commonly used locations on the filesystem.
  row_item: ^2.2.1+1
  settings_ui: ^2.0.2 # Provides a settings screen with common settings UI.
  talker_flutter: ^4.0.0 # Logging tool with UI for viewing logs.

dev_dependencies:
  build_runner: ^2.4.8 # Build and watch functionality for source generation.
  flutter_test:
    sdk: flutter # Testing utilities for Flutter.
  isar_generator: ^3.1.0+1 # Code generator for Isar, to create schemas and adapters.
  json_serializable: ^6.7.1 # Automatically generate code for converting to and from JSON.
  mocktail: ^1.0.0 # A Dart mocking library which is a simplified version of Mockito.
  objectbox_generator: any
  very_good_analysis: ^5.0.0 # A set of stricter linter rules used by Very Good Ventures.

flutter:
  uses-material-design: true # Enables Material Design widgets.
  generate: true # Enables code generation for localizations, etc.
