name: google_exporter
description: An app to export all of your google data
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.7+2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  go_router: ^13.0.1
  intl: ^0.18.1
  # isar: ^4.0.0-dev.10
  # isar_flutter_libs: ^4.0.0-dev.10
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  settings_ui: ^2.0.2
  talker_flutter: ^3.5.6
  file_picker: ^6.1.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
