// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'shared/domain/models/settings/settings_obb_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 8539815822991047959),
      name: 'SettingsComplex',
      lastPropertyId: const IdUid(4, 774008754132386571),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8275422242686836661),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 3312917217288979154),
            name: 'appLocaleString',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 2017146396042127804),
            name: 'themeString',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 774008754132386571),
            name: 'themeModeInt',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 8539815822991047959),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    SettingsComplex: EntityDefinition<SettingsComplex>(
        model: _entities[0],
        toOneRelations: (SettingsComplex object) => [],
        toManyRelations: (SettingsComplex object) => {},
        getId: (SettingsComplex object) => object.id,
        setId: (SettingsComplex object, int id) {
          object.id = id;
        },
        objectToFB: (SettingsComplex object, fb.Builder fbb) {
          final appLocaleStringOffset = fbb.writeString(object.appLocaleString);
          final themeStringOffset = fbb.writeString(object.themeString);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, appLocaleStringOffset);
          fbb.addOffset(2, themeStringOffset);
          fbb.addInt64(3, object.themeModeInt);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final appLocaleStringParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, '');
          final themeStringParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final themeModeIntParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final object = SettingsComplex(
              id: idParam,
              appLocaleString: appLocaleStringParam,
              themeString: themeStringParam,
              themeModeInt: themeModeIntParam);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [SettingsComplex] entity fields to define ObjectBox queries.
class SettingsComplex_ {
  /// see [SettingsComplex.id]
  static final id =
      QueryIntegerProperty<SettingsComplex>(_entities[0].properties[0]);

  /// see [SettingsComplex.appLocaleString]
  static final appLocaleString =
      QueryStringProperty<SettingsComplex>(_entities[0].properties[1]);

  /// see [SettingsComplex.themeString]
  static final themeString =
      QueryStringProperty<SettingsComplex>(_entities[0].properties[2]);

  /// see [SettingsComplex.themeModeInt]
  static final themeModeInt =
      QueryIntegerProperty<SettingsComplex>(_entities[0].properties[3]);
}
